Feature/shop detail
DaemonNikolay/Shop-MVVM pull request #3
Opened 2020-12-03 12:30 UTC by DaemonNikolay

2020-12-04 04:02 UTC, answerfan requested changes

2020-12-04 04:02 UTC, answerfan commented on Shop/Common/Classes/Shop/OfficeHours.swift
> +	private var _opening: Float = .zero
Поясни мне сакральный смысл этого ivar'а ручного?

2020-12-04 04:02 UTC, answerfan commented on Shop/Common/Classes/Shop/Shop.swift
>  	required init(from decoder: Decoder) throws {
зачем тебе тут кодер и декодер методы? Codable за тебя это вроде должен делать, нет?

2020-12-04 04:02 UTC, answerfan commented on Shop/Common/Helper/DataSource/DataSource.swift
> +extension DataSource: NSCopying {
Зачем NSCopying? Добавил с какой-то целью?

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/OperatingTime/OperatingTimeModule.swift
> +	let router: OperatingTimeRouter
зачем роутер торчит снаружи? Внеси его в инициализацию модуля, наружу он не нужен тут

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/OperatingTime/OperatingTimeModule.swift
> +class OperatingTimeModule {
Тут как раз можно структуру делать

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/OperatingTime/View/OperatingTimeViewController.swift
> +	@IBAction func saveClick(_ sender: UIButton) {
saveTap лучше, на телефонах и планшетах тапают, но это так, минор

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
>  class ShopDetailViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
делегат и датасорс таблицы в экстеншены и перед экстеншеном помечай // MARK: - <extension title>
Навигация по файлу облечается

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
>  struct OperatingTimeViewModel {
где протоколы взаимодействия контроллера на вьюмодель и вм на контроллер?
Ты же читал СОЛИД, но не соблюдаешь

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/OperatingTime/View/OperatingTimeViewController.swift
> +		self.setupOperatingTime()
работает это иначе - ты во вьюмодель кидаешь через протокол метод didLoad() например, в нём, если в будущем бы понадобилось, может аналитика какая, или стартовый фетч каких-то данных. И из этого didLoad() в обратном направлении уже через протокол воздействия вм на контроллер вызываешь метод сетапа времени работы, где уже и передаёшь развёрнутое значение времени

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +		Shop.DetailNames.allCases.count
править ничего не нужно.
Но, на будущее, в таких кейсах надо логику закладывать на то, что в каких-то категориях у тебя на данный момент может не быть значений. И если у тебя нет плейсхолдера, скорее всего такую секцию надо будет скрыть. Но тут время не трать

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +		cell.textLabel?.text = self.viewModel.formatPropertyOfShopBy(indexPath.row)
вообще, так делать не очень правильно(стучаться к аутлетам ячейки напрямую из контроллера).
На будущее, ты переопределяешь ячейку (в коммерческих проектах никто не работает со стандартными UITableViewCell), аутлеты приватишь и устанавливаешь значения и стэйты ячейки через один публичный метод, например, cell.setup(with: <SomeObject>)

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +		self.viewModel.actionOnCellTap(numberRow: indexPath.row,
тоже через протокол со вьюмоделью взаимодействовать нужно

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +enum ActionType {
для одного кейса енам не делают

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +	override func viewDidLoad() {
кнопки назад не хватает, чтобы выйти без сохранения

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +	@IBAction func saveClick(_ sender: UIButton) {
saveTap

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
>  struct ShopDetailViewModel {
нет протоколов ShopDetailViewModelInput и ShopDetailViewModelOutput. Первый реализуется во вьюмодели, второй - в контроллере.

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			guard let employees = UInt(value) else {
если одно условие в гварде и пустой else - пиши в одну строку

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func propertyOfShopBy(_ index: Int) -> (Shop.DetailNames?, String) {
вот этот метод вообще непонятно что делает.

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			self.dataSource.updateShop(shop: shop)
зачем ты везде пишешь self. ... ? Где можно обходиться без селф - обходись без него, идея всё равно тебе подсветит, где сторед проперти, а где - локальная переменная

2020-12-04 04:02 UTC, answerfan commented on Shop/Scenes/ShopList/ViewModel/ShopListViewModel.swift
> +		if !shop.isNearestShop {
а тут не то что бы докапываюсь, думаю, что зависит от проекта и принятого кодстайла на нём. У нас лид не любит такие проверки. Типа, очевиднее писать shop.isNearestShop == false. По мне - это дело вкуса. Но не удивляйся, если будут докапываться

2020-12-04 04:34 UTC, DaemonNikolay commented on Shop/Common/Classes/Shop/OfficeHours.swift
> +	private var _opening: Float = .zero
Зачем задаю значения на старте? У магазина не может не быть часов работы (варианты выходных не рассматриваем), из-за неплохо иметь при обращении дефолтные значения
Время работы с полуночи до полуночи, и получаем что-то типа круглосуточного

2020-12-04 04:36 UTC, DaemonNikolay commented on Shop/Common/Classes/Shop/Shop.swift
>  	required init(from decoder: Decoder) throws {
У меня не компилилось, ругался что нет реализаций для кодер и декодер

2020-12-04 04:40 UTC, DaemonNikolay commented on Shop/Common/Helper/DataSource/DataSource.swift
> +extension DataSource: NSCopying {
Нашёл статью (https://refactoring.guru/ru/design-patterns/singleton/swift/example), в ней приводился пример с NSCopying. При попытке копирования чтобы возвращался сам self. 
Я до конца не понимаю зачем нужно делать не копируемым если и так адрес один при обращении через shared, но так как ресурс рассказывает интересные вещи, то сделал по образцу.

2020-12-04 04:42 UTC, DaemonNikolay commented on Shop/Scenes/OperatingTime/OperatingTimeModule.swift
> +	let router: OperatingTimeRouter
В проекте-примере он весел наружу, сделал по эталону. Исправлю

2020-12-04 04:43 UTC, DaemonNikolay commented on Shop/Scenes/OperatingTime/OperatingTimeModule.swift
> +class OperatingTimeModule {
Исправлю

2020-12-04 04:44 UTC, DaemonNikolay commented on Shop/Scenes/OperatingTime/View/OperatingTimeViewController.swift
> +	@IBAction func saveClick(_ sender: UIButton) {
Логично, исправлю

2020-12-04 04:44 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
>  class ShopDetailViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
Исправлю

2020-12-04 04:53 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +		Shop.DetailNames.allCases.count
Это логично, скажем подгрузка из сети и данных "здесь и сейчас" не будет. В таком случае нужна заглушка, но так как, конкретно в этом случае, данные будут сразу – заглушка просто никогда не сработает

2020-12-04 05:02 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func propertyOfShopBy(_ index: Int) -> (Shop.DetailNames?, String) {
Нужно было получить читабельные имена для свойств магазина и значения этих самых свойств. Выглядит криво, но более лучшего способа не придумал на ходу

2020-12-04 05:05 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			self.dataSource.updateShop(shop: shop)
Привычка, не более

2020-12-04 05:06 UTC, DaemonNikolay commented on Shop/Scenes/ShopList/ViewModel/ShopListViewModel.swift
> +		if !shop.isNearestShop {
Напоминает времена, когда булевская переменная сама по себе не могла быть условием для сравнения. Такое касается только false или любого логического сравнения?

2020-12-04 07:02 UTC, answerfan commented on Shop/Common/Classes/Shop/OfficeHours.swift
> +	private var _opening: Float = .zero
нет, зачем это оборачивать в ivar руками?

2020-12-04 07:03 UTC, answerfan commented on Shop/Common/Classes/Shop/Shop.swift
>  	required init(from decoder: Decoder) throws {
Ты прямо уверен? Потому что у меняя прямо щас компилится без этих инитов

2020-12-04 07:06 UTC, answerfan commented on Shop/Common/Helper/DataSource/DataSource.swift
> +extension DataSource: NSCopying {
Если чего-то не понимаешь - не пиши. Либо спроси, либо разберись.
Эта конструкция нужна для атомарного копирования объекта, особенно когда у тебя многопоточная работа с данными.
У тебя тут и в помине нет такой работы. Согласно принципу YAGNI - выпиливай данную конструкцию

2020-12-04 07:07 UTC, DaemonNikolay commented on Shop/Common/Classes/Shop/Shop.swift
>  	required init(from decoder: Decoder) throws {
Интересно. Просто так их писать бы не стал, посмотрю ещё раз

2020-12-04 07:08 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func propertyOfShopBy(_ index: Int) -> (Shop.DetailNames?, String) {
а почему возвращаешь Tuple вместо просто финальной строки?

2020-12-04 07:09 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			self.dataSource.updateShop(shop: shop)
ну как минимум, короче код станет

2020-12-04 07:10 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			self.dataSource.updateShop(shop: shop)
пять

2020-12-04 07:10 UTC, answerfan commented on Shop/Scenes/ShopList/ViewModel/ShopListViewModel.swift
> +		if !shop.isNearestShop {
не уверен, не часто встречаю такие проверки, на самом деле. Но для очевидности разворачиваю для любых условий.

2020-12-04 07:19 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func propertyOfShopBy(_ index: Int) -> (Shop.DetailNames?, String) {
Ранее данный метод вызывался в двух местах и требовалось разделение данных для второго (поэтому есть отдельный метод для форматирования с превращением в единую строку), но он позже был удалён и осталось как старое
Обновлю реализацию

2020-12-04 07:20 UTC, DaemonNikolay commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func propertyOfShopBy(_ index: Int) -> (Shop.DetailNames?, String) {
Делать возвращаемое значение в виде класса/структуры было бы слишком круто для такой мелочи, поэтому просто Tuple

2020-12-07 03:35 UTC, answerfan requested changes

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopList/View/ShopListViewController.swift
> +		let viewModel = self.viewModel
зачем эта переменная?

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelOutput.swift
> +protocol ShopListViewModelOutput {
если протокол пустой - {} или { }

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelOutput.swift
> +//
вот эти стандартные комментарии, которые генерит икскод - смело выпиливай

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelInput.swift
> +//
аналогично для данного файла

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelInput.swift
> +//
И второй, более главный вопрос - почему ты сделал протоколы отдельными файлами? Это ж свифт, тут обычно протоколы в том же файле и пишутся.
Оба данных протокола кидай в интерактор, в самое начало, после импорта\импортов

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +
одну лишнюю строку отбил

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/Protocols/ShopDetailViewModelInput.swift
> +protocol ShopDetailViewModelInput {
аналогично, само объявление протоколов в интерактор.

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/Protocols/ShopDetailViewModelInput.swift
> +
А теперь - почему уже вторая пара протоколов пустая?
Ты же прекрасно знаешь, для чего они нужны. Так используй правильно. Если не понимаешь - спроси

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +			self.viewModel.showShopList()
утекает память

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +		self.viewModel.saveShop {
и это работает не так, во вьюмодели будет метод didTapSave, если надо, можно и кнопку туда передать, например.
во вьюмодели происходит бизнес-логика.
у аутпут протокола метод реакции вью на последствия тапа, этот метод из вьюмодели дёргает работу UI, в контроллере, который реализует аутпут - собственно, то действие, которое ты тут в комплишен запихал

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +
лишнюю строку отбил.

Если хочешь визуально переменные от методов отделить тут - сделай "// MARK: - Initialization" , например

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
> +extension OperatingTimeViewModel {
лучше перед экстеншенами помечать, за что каждый экстеншн овечает - // MARK: - DI Container

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
>  struct OperatingTimeViewModel {
вопрос как бы ещё актуален, потому что ты занёс мусора в код, но ситуация не исправилась

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/OperatingTime/Protocols/OperatingTimeViewModelInput.swift
> +//
аналогичные комментарии ко всем протоколам

2020-12-07 03:35 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
> +		self.currentShop = self.dataSource.currentShop
это должно передаваться снаружи, а не внутри "чудесным образом" появляться.

Ну или если ты это делаешь через сервис всё же, то в didLoad() ты узнал, что у тебя загрузилась вьюшка, там и загружай из сервиса и потом выдавай команду на обновление UI

2020-12-07 03:35 UTC, answerfan commented on Shop/Common/Helper/DataSource/DataSource.swift
>  			self.shop(id: shopId)!
зуб даёшь, что этот форсанврап никогда не свалится?

Если нет, то не ставь форсанврапы, только в аутлетах или DI

2020-12-07 03:35 UTC, answerfan commented on Shop/Common/Classes/Shop/Shop.swift
>  	required init(from decoder: Decoder) throws {
всё ещё сомневаюсь в необходимости данной пары методов

2020-12-07 03:35 UTC, answerfan commented on Shop.xcodeproj/project.pbxproj
Сделай светлую тему всегда, неудобно смотреть

2020-12-07 03:38 UTC, answerfan commented on Shop/Scenes/OperatingTime/OperatingTimeModule.swift
> +	let router: OperatingTimeRouter
проект-пример именно что "пример", не эталон. Туда можно подсматривать, но думать головой

2020-12-07 03:48 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +			if shopDetailKey == .officeHours {
условия можно в один иф, через запятую

2020-12-07 03:48 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +		case .type:
перед кейсами, кроме первого, отбивают строку обычно, чтобы было видно, что блок действий кончился

2020-12-07 03:48 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
> +				cell.tag = 1
не пользуйся тэгами - это прошлое десятилетие.

Лучше сделай кастомную ячейку, у неё свой идентификатор бахни, по которому и определяй тап как-то надо обрабатывать или нет.
Либо ещё как-то, вариантов придумать можно много

2020-12-07 03:48 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +			self.dataSource.updateShop(shop: shop)
5 символов * на сто раз в каждом файле

2020-12-07 03:53 UTC, answerfan requested changes

2020-12-07 03:53 UTC, answerfan commented on Shop/Common/Classes/Shop/Shop.swift
> +	var isNearestShop: Bool
у меня старая версия, где данного параметра не было, при накате новой версии - падает, думаю из-за форсанврапа и изменении модели

2020-12-07 04:20 UTC, DaemonNikolay commented on Shop/Scenes/ShopList/View/ShopListViewController.swift
> +		let viewModel = self.viewModel
Чтобы ниже использовать viewModel вместо self.viewModel... как-то тупо, исправлю

2020-12-07 04:20 UTC, DaemonNikolay commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelInput.swift
> +//
Разделение для личного удобства. Протокол, класс, структура – отдельный файл
Сделаю

2020-12-08 02:37 UTC, answerfan commented on Shop/Scenes/ShopList/Protocols/ShopListViewModelInput.swift
> +//
излишне, на мой взгляд. Но тут настаивать не буду. Просто в коммерческих проектах в основном видел именно так, что протоколы прямо рядом с тем, где используются, лежат

2020-12-08 11:36 UTC, answerfan requested changes

2020-12-08 11:36 UTC, answerfan commented on Shop/Common/Classes/Shop/OfficeHours.swift
> +	init(opening: Float = .zero, closing: Float = .zero) {
Я ничего против дефолтных значений не имею. Но знай, что на некоторых проектах могут встретиться лиды, которые не любят дефолтные значения в силу их неочевидности)
Как прочитаешь - резолви данный комментарий

2020-12-08 11:36 UTC, answerfan commented on Shop/Common/Helper/DataSource/AutoFillDB.swift
> +        if dataSource.shopCount > 0 {
Этот иф можно превратить в гвард элс, чтобы убрать вложенность

2020-12-08 11:36 UTC, answerfan commented on Shop/Common/Helper/DataSource/AutoFillDB.swift
> +            if !dataSource.validShopsOnExistIsNearest() {
и тут, может быть, надо попробовать гвардом обработать

2020-12-08 11:36 UTC, answerfan commented on Shop/Common/Helper/DataSource/DataSource.swift
> +class DataSource {
кстати, тут не дискасс, ерундой уже заниматься не будем.
Но, те классы, которые уже не будешь наследовать (как этот датасорс, например), делай final. Напрямую влияет на диспетчеризацию и, как следствие, на скорость работы

Как прочитаешь комментарий - резолви.
Если надо будет инфо про диспетчеризацию - напиши мне, создам в трелло карточку

2020-12-08 11:36 UTC, answerfan commented on Shop/Scenes/OperatingTime/View/OperatingTimeViewController.swift
> +	private var viewModel: OperatingTimeViewModel
должно быть так - `private var viewModel: OperatingTimeViewModelInput`

2020-12-08 11:36 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
> +	private let router: OperatingTimeRouter
по-хорошему, для поддержания стройности и единого стиля архитектуры, надо бы тут ещё `private weak var view: OperatingTimeViewModelOutput` и метод публичный setup(view: UIViewController) для установки в модуль файле

2020-12-08 11:36 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
> +	func extractDateFrom(_ time: Float) -> Date
опять же, не дискасс, как прочитаешь - закроешь.
Но некоторые лиды в компании не любят в такой структуре возвратных значений. Обходят тем, что в аутпут протоколе возвращают методом значения и выполняют то, что у тебя там дальше в контроллере и идёт.
С одной стороны, при таком подходе потом затаскивать Rx попроще, но я криминала в твоём подходе тоже не вижу

2020-12-08 11:36 UTC, answerfan commented on Shop/Scenes/ShopDetail/View/ShopDetailViewController.swift
>  	private var viewModel: ShopDetailViewModel
так же, протоколом тут объявляй, ты о вьюмодели должен знать только то, что есть в интерфейсе инпута

2020-12-08 11:36 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +protocol ShopDetailViewModelOutput {
ты не понял смысла данного протокола. Эти методы вызывает вьюмодель, а реализуются они во вьюконтроллере, т.е. во вьюмодели у тебя должна быть слабая ссылка `private weak var view: ShopDetailViewModelOutput `, и потом вызывать `view.displayShop(with items: [Shop])`, например

2020-12-08 11:43 UTC, answerfan requested changes

2020-12-08 11:43 UTC, answerfan commented on Shop/Scenes/OperatingTime/ViewModel/OperatingTimeViewModel.swift
> +		currentShop = dataSource.currentShop
вся эта работа с currentShop должна быть в didLoad()

2020-12-09 06:51 UTC, answerfan requested changes

2020-12-09 06:51 UTC, answerfan commented on Shop/Scenes/OperatingTime/View/OperatingTimeViewController.swift
> +		openingTime.date = viewModel.extractDateFromOpeningTime() ?? Date()
эта логика должна была быть во вьюмодели, ты из вьюмодели должен был вернуть уже неопциональные значения, по-хорошему. но уже не правь, как прочитаешь - закроешь дискасс

2020-12-09 06:51 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	mutating func didLoad()
зачем mutating?

2020-12-09 06:51 UTC, answerfan commented on Shop/Scenes/ShopDetail/ViewModel/ShopDetailViewModel.swift
> +	func fillCellBy(_ indexPath: IndexPath,
этот метод во вьюмодели не особо нужен, ты должен был в контроллер выдать данные и сделать релоад - сами данные в датасорсе и ставить (если ячейка кастомная - то сетап в ней самой, ей на вход необходимые данные только дать)

2020-12-09 06:51 UTC, answerfan commented on Shop/Scenes/ShopList/View/ShopListViewController.swift
> +		viewModel.rowsCount()
это тоже, по-хорошему, раньше где-то должно было быть получено из вьюмодели, сохранено в контроллере и дальше дёрнут релоад из контроллера. Так ты завязываешь на вьюмодель.
Но тоже уже не правь, просто закрой

2020-12-09 08:19 UTC, merged